// MediaGit - Git for Media Files
// Copyright (C) 2025 MediaGit Contributors
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Affero General Public License for more details.

//! DC-7/D4: where the server keeps the repository keys clients escrow with it.
//!
//! # Why the server holds keys at all
//!
//! The threat model is a compromised **object store** — an exposed bucket,
//! stolen backups, the cloud provider — not a compromised server. The server is
//! inside the trust boundary and has to be: five of its code paths read object
//! plaintext, four of them re-deriving `BLAKE3(plaintext)` because that is what
//! a chunk id *is*, and `collect_objects_bfs` walking commits and trees to
//! decide what a clone should receive. None of that can run on ciphertext.
//!
//! Note this is *not* the reason recorded in `todo.md` for most of DC-7's life,
//! which said the server computes chunk deltas and would lose the ~26.5%
//! savings without plaintext. It does not compute deltas — every
//! `DeltaEncoder::encode` call site is client-side, and the server stores
//! client-computed deltas verbatim.
//!
//! # Shape
//!
//! Two keys, mirroring the client's arrangement in `mediagit-cli`:
//!
//! * a **repo key**, generated by the client, escrowed here, the key every
//!   object in that repository is sealed under;
//! * a **server master key**, read from a file named in the server's config,
//!   used only to wrap repo keys at rest.
//!
//! Without the master key the server would have to keep repo keys in the clear
//! on its own disk — and the object store credentials it is protecting against
//! usually live on that same disk, which would make the whole feature theatre.
//! Hence [`ServerConfig`]'s `[encryption] enabled` requiring `master_key_path`.
//!
//! # On disk — `<repo>/.mediagit/key.json`
//!
//! ```json
//! {
//!   "version": 1,
//!   "wrapped": "<hex>",      // MGEN envelope over the 32-byte repo key
//!   "fingerprint": "<hex>"   // BLAKE3(repo key)
//! }
//! ```
//!
//! The fingerprint is what lets the escrow endpoint answer "is this the same
//! key you already hold?" without either side putting a key in the clear, and
//! it is checked after every unwrap: AES-GCM is not key-committing, so
//! authentication alone does not promise a ciphertext opens under exactly one
//! key.

use anyhow::{Context, Result, anyhow, bail};
use mediagit_security::encryption::EncryptionKey;
use mediagit_security::{Zeroizing, envelope};
use serde::{Deserialize, Serialize};
use std::path::{Path, PathBuf};

use crate::config::EncryptionConfig;

/// Domain-separation context for wrapping repo keys under the server master.
///
/// Deliberately different from the client's `mediagit/wrap/v2`: the two wrap
/// the same repo key under different masters for different reasons, and a
/// shared context would let one context's ciphertext be presented to the other.
const WRAP_CONTEXT: &str = "mediagit/server-wrap/v2";

/// Repo/master key length — AES-256.
const KEY_LEN: usize = 32;

/// File name under a repository's `.mediagit/`.
const KEY_FILE: &str = "key.json";

/// The escrowed repo key as it sits on the server's disk. Holds no usable key
/// material on its own: `wrapped` is ciphertext under the server master key.
#[derive(Debug, Serialize, Deserialize)]
struct StoredRepoKey {
    version: u32,
    wrapped: String,
    fingerprint: String,
}

/// Where a repository's escrowed key lives.
pub fn key_file_path(repo_path: &Path) -> PathBuf {
    repo_path.join(".mediagit").join(KEY_FILE)
}

/// Read the server master key named by the config.
///
/// `Ok(None)` means encryption is switched off, which is the default and must
/// stay completely silent — the overwhelming majority of servers run this way
/// and must behave exactly as they did before DC-7.
///
/// Accepts the same two spellings the client does: 64 hex characters, or 32 raw
/// bytes. Anything else is a hard error rather than a guess, because a
/// mis-parsed master key would wrap every repo key under something nobody can
/// reproduce.
pub fn load_master_key(cfg: &EncryptionConfig) -> Result<Option<EncryptionKey>> {
    if !cfg.enabled {
        return Ok(None);
    }
    let Some(path) = cfg.master_key_path.as_deref() else {
        // Reached only if this is called without `verify_startup_config`
        // having run first; kept as a real error rather than an unwrap so the
        // ordering is not load-bearing.
        bail!(
            "[encryption] enabled = true but no master_key_path is set. \
             Repository keys would have to be stored in the clear."
        );
    };
    Ok(Some(read_key_file(path)?))
}

/// Fail before serving, not on the first encrypted push.
///
/// A server that starts with encryption "on" and no usable master key would
/// accept escrow requests it cannot honour, and the operator would find out
/// from a user. Called from `main` before the listener binds.
pub fn verify_startup_config(cfg: &EncryptionConfig) -> Result<()> {
    if !cfg.enabled {
        return Ok(());
    }
    let Some(path) = cfg.master_key_path.as_deref() else {
        bail!(
            "[encryption] enabled = true, but master_key_path is not set.\n\
             \n\
             The server wraps every repository key it stores under this master key. \
             Without it those keys would sit in the clear on this machine — usually \
             the same machine that holds the object store credentials this feature \
             exists to protect against. Set [encryption] master_key_path, or set \
             enabled = false."
        );
    };
    read_key_file(path).with_context(|| {
        format!(
            "[encryption] master_key_path = {} could not be read as a master key",
            path.display()
        )
    })?;
    Ok(())
}

/// Parse a 32-byte key from a file, as hex or raw bytes.
fn read_key_file(path: &Path) -> Result<EncryptionKey> {
    // Zeroized regardless of which arm fires: the hex arm's buffer is the
    // master key spelled out in ASCII, which is exactly as sensitive as the
    // raw form.
    let raw = Zeroizing::new(
        std::fs::read(path).with_context(|| format!("reading master key at {}", path.display()))?,
    );

    let bytes = match std::str::from_utf8(&raw).map(str::trim) {
        Ok(text) if text.len() == KEY_LEN * 2 => Zeroizing::new(
            hex::decode(text).with_context(|| format!("{} is not valid hex", path.display()))?,
        ),
        _ if raw.len() == KEY_LEN => Zeroizing::new(raw.to_vec()),
        _ => bail!(
            "{} must contain a 32-byte key, either as {} hex characters or {KEY_LEN} raw bytes",
            path.display(),
            KEY_LEN * 2
        ),
    };
    EncryptionKey::from_bytes(bytes.to_vec()).map_err(|e| anyhow!("{}: {e}", path.display()))
}

/// Does this repository have an escrowed key?
///
/// A filesystem check with no unwrapping, so it is cheap enough for paths that
/// only need to know whether a repository is encrypted at all.
pub fn has_escrowed_key(repo_path: &Path) -> bool {
    key_file_path(repo_path).exists()
}

/// The BLAKE3 fingerprint of the escrowed key, without unwrapping it.
///
/// This is what makes the escrow endpoint idempotent: re-sending the same key
/// is a no-op, sending a different one is a conflict, and neither answer
/// requires the server to hold two keys in the clear to compare them.
pub fn escrowed_fingerprint(repo_path: &Path) -> Result<Option<String>> {
    let path = key_file_path(repo_path);
    if !path.exists() {
        return Ok(None);
    }
    Ok(Some(read_stored(&path)?.fingerprint))
}

/// Wrap `repo_key` under the server master and write it beside the repository.
///
/// Refuses to overwrite a *different* key: every object already stored is
/// sealed under the one on disk, and nothing records which key an object used,
/// so replacing it would orphan the repository silently and completely.
/// Re-storing the same key is a no-op, which is what makes a retried escrow
/// upload safe.
pub fn store_repo_key(repo_path: &Path, master: &EncryptionKey, repo_key: &[u8]) -> Result<()> {
    if repo_key.len() != KEY_LEN {
        bail!(
            "escrowed repository key must be {KEY_LEN} bytes, got {}",
            repo_key.len()
        );
    }
    let fingerprint = blake3::hash(repo_key).to_hex().to_string();

    let path = key_file_path(repo_path);
    if let Some(existing) = escrowed_fingerprint(repo_path)? {
        if existing == fingerprint {
            return Ok(());
        }
        bail!(
            "this repository already has a different escrowed key. Replacing it would \
             make every object already stored unreadable, so it will not be replaced."
        );
    }

    let wrap_key = master
        .derive_subkey(WRAP_CONTEXT)
        .map_err(|e| anyhow!("deriving the server wrapping subkey: {e}"))?;
    let stored = StoredRepoKey {
        version: 1,
        wrapped: hex::encode(
            envelope::seal(&wrap_key, repo_key)
                .map_err(|e| anyhow!("wrapping the escrowed repo key: {e}"))?,
        ),
        fingerprint,
    };
    write_atomic(&path, &stored)
}

/// Unwrap this repository's escrowed key.
///
/// `Ok(None)` means the repository is not encrypted, which is silent and cheap
/// — the common case.
pub fn load_repo_key(repo_path: &Path, master: &EncryptionKey) -> Result<Option<EncryptionKey>> {
    let path = key_file_path(repo_path);
    if !path.exists() {
        return Ok(None);
    }
    let stored = read_stored(&path)?;

    let wrap_key = master
        .derive_subkey(WRAP_CONTEXT)
        .map_err(|e| anyhow!("deriving the server wrapping subkey: {e}"))?;
    let wrapped =
        hex::decode(stored.wrapped.trim()).context("key.json: `wrapped` is not valid hex")?;

    // Authenticated: a wrong master key fails here rather than yielding 32
    // bytes of garbage that would then be used to "decrypt" the repository.
    let bytes = Zeroizing::new(envelope::open(&wrap_key, &wrapped).map_err(|_| {
        anyhow!(
            "could not unwrap {}'s escrowed key with this server's master key. \
             The master key has changed, or this key file belongs to another server.",
            repo_path.display()
        )
    })?);

    // AES-GCM is not key-committing, so authentication alone does not promise
    // this ciphertext opens under exactly one key.
    let actual = blake3::hash(&bytes).to_hex();
    if actual.as_str() != stored.fingerprint {
        bail!(
            "key.json: the unwrapped repository key does not match its recorded \
             fingerprint — the file may be corrupted or tampered with"
        );
    }

    let key = EncryptionKey::from_bytes(bytes.to_vec())
        .map_err(|e| anyhow!("key.json: unwrapped key is unusable: {e}"))?;
    Ok(Some(key))
}

fn read_stored(path: &Path) -> Result<StoredRepoKey> {
    let text =
        std::fs::read_to_string(path).with_context(|| format!("reading {}", path.display()))?;
    let stored: StoredRepoKey =
        serde_json::from_str(&text).with_context(|| format!("parsing {}", path.display()))?;
    if stored.version != 1 {
        bail!(
            "{} was written by a newer MediaGit (format version {}); upgrade to read it",
            path.display(),
            stored.version
        );
    }
    Ok(stored)
}

/// Write via a temporary file and rename, so a crash mid-write cannot leave a
/// half-written key file where a whole one used to be.
fn write_atomic(path: &Path, stored: &StoredRepoKey) -> Result<()> {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)
            .with_context(|| format!("creating {}", parent.display()))?;
    }
    let tmp = path.with_extension("json.tmp");
    let json = serde_json::to_string_pretty(stored)?;
    std::fs::write(&tmp, json).with_context(|| format!("writing {}", tmp.display()))?;
    restrict_permissions(&tmp);
    if let Err(e) = std::fs::rename(&tmp, path) {
        // Otherwise a failed rename leaves a second copy of the wrapped key
        // behind, with whatever permissions the directory hands out.
        let _ = std::fs::remove_file(&tmp);
        return Err(e).with_context(|| format!("renaming {} into place", tmp.display()));
    }
    restrict_permissions(path);
    Ok(())
}

#[cfg(unix)]
fn restrict_permissions(path: &Path) {
    use std::os::unix::fs::PermissionsExt;
    let _ = std::fs::set_permissions(path, std::fs::Permissions::from_mode(0o600));
}

#[cfg(not(unix))]
fn restrict_permissions(_path: &Path) {}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    fn master() -> EncryptionKey {
        EncryptionKey::from_bytes(vec![0x7au8; KEY_LEN]).unwrap()
    }

    fn write_master_file(dir: &Path, byte: u8) -> PathBuf {
        let p = dir.join("master.key");
        std::fs::write(&p, hex::encode(vec![byte; KEY_LEN])).unwrap();
        p
    }

    #[test]
    fn a_repo_with_no_escrowed_key_loads_nothing() {
        let dir = TempDir::new().unwrap();
        assert!(!has_escrowed_key(dir.path()));
        assert!(load_repo_key(dir.path(), &master()).unwrap().is_none());
        assert!(escrowed_fingerprint(dir.path()).unwrap().is_none());
    }

    #[test]
    fn an_escrowed_key_round_trips() {
        let dir = TempDir::new().unwrap();
        let repo_key = vec![0x5cu8; KEY_LEN];
        store_repo_key(dir.path(), &master(), &repo_key).unwrap();

        assert!(has_escrowed_key(dir.path()));
        let loaded = load_repo_key(dir.path(), &master()).unwrap().unwrap();
        assert_eq!(loaded, EncryptionKey::from_bytes(repo_key.clone()).unwrap());
        assert_eq!(
            escrowed_fingerprint(dir.path()).unwrap().unwrap(),
            blake3::hash(&repo_key).to_hex().to_string()
        );
    }

    #[test]
    fn the_stored_file_holds_ciphertext_not_the_key() {
        let dir = TempDir::new().unwrap();
        let repo_key = vec![0xa1u8; KEY_LEN];
        store_repo_key(dir.path(), &master(), &repo_key).unwrap();

        let raw = std::fs::read(key_file_path(dir.path())).unwrap();
        assert!(
            !raw.windows(KEY_LEN).any(|w| w == repo_key.as_slice()),
            "the repo key must not appear in the file that wraps it"
        );
        assert!(
            !String::from_utf8_lossy(&raw).contains(&hex::encode(&repo_key)),
            "nor in its hex spelling"
        );
    }

    #[test]
    fn re_escrowing_the_same_key_is_a_no_op() {
        let dir = TempDir::new().unwrap();
        let repo_key = vec![0x33u8; KEY_LEN];
        store_repo_key(dir.path(), &master(), &repo_key).unwrap();
        // A retried upload must not be an error: the client cannot always tell
        // whether its first attempt landed.
        store_repo_key(dir.path(), &master(), &repo_key).unwrap();
        assert_eq!(
            load_repo_key(dir.path(), &master()).unwrap().unwrap(),
            EncryptionKey::from_bytes(repo_key).unwrap()
        );
    }

    #[test]
    fn escrowing_a_different_key_is_refused() {
        let dir = TempDir::new().unwrap();
        store_repo_key(dir.path(), &master(), &[0x01u8; KEY_LEN]).unwrap();
        let err = store_repo_key(dir.path(), &master(), &[0x02u8; KEY_LEN]).unwrap_err();
        assert!(
            err.to_string()
                .contains("already has a different escrowed key")
        );
        // And the original is untouched.
        assert_eq!(
            load_repo_key(dir.path(), &master()).unwrap().unwrap(),
            EncryptionKey::from_bytes(vec![0x01u8; KEY_LEN]).unwrap()
        );
    }

    #[test]
    fn the_wrong_master_key_fails_closed() {
        let dir = TempDir::new().unwrap();
        store_repo_key(dir.path(), &master(), &[0x77u8; KEY_LEN]).unwrap();

        let other = EncryptionKey::from_bytes(vec![0x11u8; KEY_LEN]).unwrap();
        let err = load_repo_key(dir.path(), &other).unwrap_err();
        assert!(
            err.to_string().contains("could not unwrap"),
            "a wrong master must be an error, never 32 bytes of garbage: {err}"
        );
    }

    #[test]
    fn a_tampered_fingerprint_fails_closed() {
        let dir = TempDir::new().unwrap();
        store_repo_key(dir.path(), &master(), &[0x44u8; KEY_LEN]).unwrap();

        let path = key_file_path(dir.path());
        let mut stored: StoredRepoKey =
            serde_json::from_str(&std::fs::read_to_string(&path).unwrap()).unwrap();
        stored.fingerprint = blake3::hash(b"something else").to_hex().to_string();
        std::fs::write(&path, serde_json::to_string_pretty(&stored).unwrap()).unwrap();

        let err = load_repo_key(dir.path(), &master()).unwrap_err();
        assert!(err.to_string().contains("does not match its recorded"));
    }

    #[test]
    fn encryption_is_off_by_default_and_silent() {
        let cfg = EncryptionConfig::default();
        assert!(!cfg.enabled);
        assert!(load_master_key(&cfg).unwrap().is_none());
        verify_startup_config(&cfg).expect("a server with encryption off must start");
    }

    #[test]
    fn enabling_encryption_without_a_master_key_refuses_to_start() {
        let cfg = EncryptionConfig {
            enabled: true,
            master_key_path: None,
        };
        let err = verify_startup_config(&cfg).unwrap_err();
        assert!(
            err.to_string().contains("master_key_path is not set"),
            "the operator must be told what to fix: {err}"
        );
    }

    #[test]
    fn enabling_encryption_with_an_unreadable_master_key_refuses_to_start() {
        let dir = TempDir::new().unwrap();
        let cfg = EncryptionConfig {
            enabled: true,
            master_key_path: Some(dir.path().join("does-not-exist.key")),
        };
        assert!(verify_startup_config(&cfg).is_err());

        // And a file that exists but is not a key is just as fatal — finding
        // out at the first encrypted push would be far worse.
        let junk = dir.path().join("junk.key");
        std::fs::write(&junk, "not a key").unwrap();
        let cfg = EncryptionConfig {
            enabled: true,
            master_key_path: Some(junk),
        };
        assert!(verify_startup_config(&cfg).is_err());
    }

    #[test]
    fn a_configured_master_key_loads() {
        let dir = TempDir::new().unwrap();
        let cfg = EncryptionConfig {
            enabled: true,
            master_key_path: Some(write_master_file(dir.path(), 0x9e)),
        };
        verify_startup_config(&cfg).unwrap();
        let key = load_master_key(&cfg).unwrap().unwrap();
        assert_eq!(
            key,
            EncryptionKey::from_bytes(vec![0x9eu8; KEY_LEN]).unwrap()
        );
    }
}
