#!/usr/bin/env bash
# Conventional Commits message validator
# Format: type(scope): description
#
# Allowed types:
#   feat, fix, docs, style, refactor, perf, test, build, ci, chore, revert
#
# Examples:
#   feat: add chunked upload support
#   fix(cli): resolve Windows path handling
#   docs(guide): update storage backend section
#   chore!: drop support for Rust 1.80

commit_msg_file="$1"
commit_msg=$(head -1 "$commit_msg_file")

# Allow merge commits and revert commits generated by git
if echo "$commit_msg" | grep -qE "^(Merge|Revert) "; then
  exit 0
fi

# Conventional commit pattern: type(optional-scope)!?: description
pattern="^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)(\([a-z0-9_-]+\))?!?: .{1,}"

if ! echo "$commit_msg" | grep -qE "$pattern"; then
  echo ""
  echo "❌ Invalid commit message format!"
  echo ""
  echo "Expected: type(scope): description"
  echo ""
  echo "Allowed types:"
  echo "  feat     - New feature"
  echo "  fix      - Bug fix"
  echo "  docs     - Documentation changes"
  echo "  style    - Code style (formatting, no logic change)"
  echo "  refactor - Code refactoring"
  echo "  perf     - Performance improvement"
  echo "  test     - Adding/fixing tests"
  echo "  build    - Build system or dependencies"
  echo "  ci       - CI/CD changes"
  echo "  chore    - Maintenance tasks"
  echo "  revert   - Revert a previous commit"
  echo ""
  echo "Examples:"
  echo "  feat: add chunked upload support"
  echo "  fix(cli): resolve Windows path handling"
  echo "  docs(guide): update storage backend section"
  echo ""
  echo "Your message: \"$commit_msg\""
  echo ""
  exit 1
fi

# Check description length (max 72 chars for the first line)
if [ ${#commit_msg} -gt 72 ]; then
  echo ""
  echo "⚠️  Commit message first line is too long (${#commit_msg} chars, max 72)"
  echo "  Tip: Keep the subject line concise, use the body for details."
  echo ""
  exit 1
fi

# Check description is not empty after the type prefix
desc=$(echo "$commit_msg" | sed -E 's/^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)(\([a-z0-9_-]+\))?!?: //')
if [ -z "$desc" ]; then
  echo "❌ Commit message description cannot be empty!"
  exit 1
fi
